# main text of home
title: "Albert Catalan Tatjer â€“ Machine Learning Efficiency"
bio: ðŸ—»
collections:
    news:
        output: true
    papers:
        output: true
    code:
        output: true

analytics_google: 'G-R6557GM4YT'